matrix:
  include:
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode8.3
rvm:
  - 2.5.1
cache: bundler
before_install:
  - brew update
script:
  - ./metanorma-setup
  - plantuml -testdot
