#!/bin/sh

cd ~
curl --remote-name https://raw.githubusercontent.com/riboseinc/metanorma-macos-setup/master/mac
curl --remote-name https://raw.githubusercontent.com/riboseinc/metanorma-macos-setup/master/Brewfile
/usr/bin/env bash mac 2>&1 | tee ~/laptop.log
